### ISSUE TITLE
Enable the Home Assistant API

### ISSUE THREAD

**Issue by michae1a1ee** [isaa-ctaylor/ha-controller#10]
Hello.
I've done all the steps outlined... Have the app on my Sense, have the token and https access to my HA installation.  But... The app is not connecting, just says "Phoning home..." on the screen.  So I'm guessing step two, enabling Home Assistant API is not actually done.  I've looked at the support pages but don't understand what needs to be done to enable the API.  Can you provide some direction?

**Comment by isaa-ctaylor** [comment]
Hi,

Can you confirm what you put as your URL in the settings? (feel free to redact any IPs/domains)

If you are using the web frontend the api is enabled by default, if not, you may have to add `api:` to the bottom of your configuration.yaml, and restart HA. This can be done with the File editor add-on [(Settings > Addons > Addon store > File editor)](https://my.home-assistant.io/redirect/supervisor_addon/?addon=core_configurator)

**Comment by michae1a1ee** [comment]
Hi, thanks for getting back to me quickly.

In the settings, for Home Assistant URL I have just entered:
1234567.xyz
(Number changed, but I have a numeric domain name with SSL and have not
included https:// as per the instructions.
The API Key has been pasted in and replaced with asterisks.  One thing I've
thought about is I created the API Key a few days ago before I added the
https access to my Home Assistant installation. Does that matter?  Do I
need to recreate the long lived access token?

I am using the web UI to access Home Assistant all the time, but part of my
troubleshooting last was adding api: to my configuration.yaml file.  It
didn't seem to help.  I'm at a loss for what the issue might be at this
point.

**Comment by isaa-ctaylor** [comment]
Does the app work if you open it, wait 5 seconds, then close it and open it again? I have a feeling that it may be down to latency issues between your watch and device. If this is the case, I can have a look at the handshake between watch and device, and try and make it more robust

**Comment by michae1a1ee** [comment]
No, that isn't working either.  I've tried pressing the Sense side button after a few seconds of "Phoning home...." on the screen to close out of the app.  Then I try to open it again.  Still just the Phoning home screen, which I haven't gotten past even once.
I also created a new API Key today, put it into HA Controller, restarted Home Assistant.  That didn't make a difference.
I have the **api:** entry in my configuration.yaml file, relatively close to the top.  Not sure if placement makes any difference but it is in there.
![image](https://github.com/isaa-ctaylor/ha-controller/assets/163686604/45af2c22-8500-4cf0-8b08-d5d6b3560dd1)

**Comment by isaa-ctaylor** [comment]
Just to check you have smart lights set up in home assistant? Currently the app only supports lights, but other devices are on the roadmap.

If you do have lights set up - I will look at the code tomorrow morning and try and make the communication between app and watch more robust.

Can you let me know what watch and phone combination you have?

**Comment by michae1a1ee** [comment]
I definitely have lights.  That's primarily what I have in Home Assistant so far:  a bunch of old X10 lights and some newer WIFI light bulbs and strips.
![image](https://github.com/isaa-ctaylor/ha-controller/assets/163686604/e24b019b-4345-46b0-be0c-d83c95633aa4)

**Comment by isaa-ctaylor** [comment]
I'll take a look at the opening negotiation between the watch and app tomorrow morning and see what I can do

**Comment by isaa-ctaylor** [comment]
Hey, apologies for not getting back to you.

The initial solution I devised was very quick and dirty, something to get it working on my device. After looking at the code, it is clear to me that a rewrite for stability's sake as well as a reformatted homescreen is in order, which unfortunately means I won't be able to provide a quick fix for your issue, as it will take a few days/weeks to rewrite the code.

I will be sure to let you know in this issue when the new version is available, and hopefully it will fix your issues. Sorry again that I can't provide a quicker solution.

(Alternatively, if you are up for it, I could walk you through sideloading the app onto your Sense in order to gain access to the console, which might shed some light on the matter...)

**Comment by michae1a1ee** [comment]
If there is anything you want me to try, as in side-loading a different version or whatever you're thinking, just let me know and I'll give it a try.  Like you said though, I'll need direction as to how to do that.

**Comment by isaa-ctaylor** [comment]
Hey, just thought I'd bring you an update - I am working on rewriting the app in my spare time, which is minimal at the moment due to exams... You are not forgotten!

Out of curiosity, would you prefer if devices were listed grouped by device type or room/area? I can think of pros and cons for both so am a bit undecided... Let me know!

**Comment by michae1a1ee** [comment]
Definitely pros and cons to both but my vote would be to group by room.  If you're in a single room in your house it is nicer to have everything you can control in that room in front of you.

**Comment by isaa-ctaylor** [comment]
Great - I was leaning towards room too. Maybe down the line I can add support for both with a toggle in the settings to serve both cases

**Comment by isaa-ctaylor** [comment]
It's suddenly occurred to me what your issue might be. As shown in your screenshot, it looks like you have quite a lot of lights set up in Home Assistant, I think the issue was that the interface between your phone and watch has a maximum size of data that can be transferred, and with the number of devices you have, it is very likely it was hitting that upper limit. I only have a small number of devices so obviously never ran into this error but the new solution should take care of this case.

**Comment by isaa-ctaylor** [comment]
Hey, I have pushed a fix and submitted it for review on the Fitbit app store, will let you know when the update is live. I've also added support for switches and buttons, if you have any! Let me know if you have any other issues after this update and I will try to get to them promptly!

**Comment by michae1a1ee** [comment]
I just took a look at the Fitbit app and the Gallery section with the
apps.  I'm not sure I've ever updated a Fitbit Sense app.  Does it work
automatically when a new version is out?  Or do I need to uninstall a
currently installed version to apply a new one?  Do you know?

**Comment by isaa-ctaylor** [comment]
I think it is supposed to happen automatically, although I have had to click update on a few apps. The update has to go through Fitbit's moderation before it is launched on the app store, which took about a week on the first publish. Will let you know when it goes live and you should be able to see the current version number on the app page to verify if it has updated correctly.

**Comment by isaa-ctaylor** [comment]
Hey, looks like the review took a few more days than expected, but is now live on the app gallery. Please let me know if this version your issues

**Comment by michae1a1ee** [comment]
> Hey, looks like the review took a few more days than expected, but is now live on the app gallery. Please let me know if this version your issues

The new version is working.  I updated and can now log into my HA installation from the Fitbit Sense.
The issues I'm seeing right now are that some of my lights are showing on the Sense with No Area defined, even though in HA I can see the Area they've been assigned to.  Also, some lights are showing as entity names.  I presume I need to populate some other field(s) in HA to correct this.  Will have to take a look at my HA installation closer and see if I can get more devices to show up properly on the Sense, but if you have any guidance as to what I might need to clean up in HA, please let me know.

**Comment by isaa-ctaylor** [comment]
That's great to hear. I ran into the same problem as you regarding naming and areas, the fix is to explicitly set the names and areas of the devices that use the wrong areas/names. Despite the toggle on some entities being set to use same area as device, I'm not sure that is internally reflected on the Home Assistant API - and therefore not reflected on the watch. Hopefully in a further update I will be able to find a way to retrieve this information dynamically. Please see screenshot below with an example explicit configuration:

![](https://cdn.isaactaylor.xyz/TTEbf9)

Let me know if this works (at your scale it might be a bit tedious, sorry!) and I will mark this issue as resolved.

**Comment by michae1a1ee** [comment]
Thank you.  I'm starting to populate the "Name" field with proper names, and disabling the "Use device area" toggle where needed allowing me to manually pick it.  This is correcting the issue.
I'd also like to put in a suggestion/wish list to change the app icon/logo to the Home Assistant logo now that it's not only for light bulbs.  I think that would look cooler on the watch to have the Home Assistant logo instead.
Overall, a great update.  Thank you for making these changes to your app!

**Comment by isaa-ctaylor** [comment]
I have thought about it, however the Home Assistant logo is not creative commons licensed so I will have to get in contact with them. I'm glad this update resolved your issue, feel free to open a new issue if you come across any other bugs!
