### ISSUE TITLE
Does it work on local network? The screen on the watch just says "Phoning home"

### ISSUE THREAD

**Issue by JPFrancoia** [isaa-ctaylor/ha-controller#12]
**Describe the bug**

I'm not entirely sure this use case is supported :) I have an instance of home assistant running on a "local" network. It's just my home network, so it's in 192.*.*.*. The long story is that it's running on a Kubernetes cluster, and the service is a Node with a port accessible only from the same network. I generated SSL certificates for this HA instance (to enable encrypted traffic), and this certificate is installed on my phone.  I can access my HA from my phone with the official app.

**To Reproduce**

- I entered the url in the app settings: 192.168.0.103:8123
- I entered a freshly generated long-lived token
- I enabled the home assistant API (at least I think I did...) by adding `api:` at the end of my config, and I restarted the HA instance
- I installed the app on my fitbit sense and tried to open it. It just says "phoning home"
- My phone is connected to the wifi and the wifi is setup on my watch too

**Expected behavior**

I expected the app on the watch to go past the "phoning home" screen

**Smartphone (please complete the following information):**
 - OS: Android

**Fitbit device (please complete the following information):**
 - Device: Fitibit sense

**Comment by isaa-ctaylor** [comment]
Hey, are you able to access your Home Assistant web interface using the url [https://192.168.0.103:8123](https://192.168.0.103:8123)? Also, roughly how many light entities do you have in your Home Assistant setup? There is a known issue regarding a large number of devices that I have a fix in the works for.

**Comment by JPFrancoia** [comment]
hey,

> are you able to access your Home Assistant web interface using the url https://192.168.0.103:8123/

Yes, but from a desktop browser and I believe I ignore the certificate warning message in my browser. My certificate isn't signed by a 3rd party (since I'm running this on a local network without any domain name attached). On phones, you can't even ignore this warning in normal browsers anymore. I had to manually add my certificate to my Android phone.

> roughly how many light entities do you have in your Home Assistant setup?

Lights, not a lot. Less than 5. Other entities: tons.

**Comment by isaa-ctaylor** [comment]
This is probably due to the certificate, I have a release coming soon to address some other issues with a large number of supported entities, and will add a toggle to switch between http (for local IPs) and https (for externally accessible instances)

**Comment by isaa-ctaylor** [comment]
After looking at the documentation, it appears that the Fitbit WebSocket implementation only supports wss:// (secure websocket). Unfortunately due to this limitation the only way I can see it working is with a 3rd party signed certificate on a secure domain name, with the Home Assistant instance accessible from outside your home network.

If you don't want to enable port forwarding within your home network, I can suggest [Cloudflare Tunnels](https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/) paired with a cheap domain, which is what I use to access my installation.

I will continue to try and find a way to support local IPs, but the Fitbit documentation is sadly lacking...

**Comment by JPFrancoia** [comment]
No worries, I suspected it would land on something like that. Thank you!
